# harness.io/skip-file-for-deploy
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.name }}-{{ .Values.environment}}-{{ .Values.datacenter }}-certs"
  namespace: "{{ .Values.namespace }}"
  annotations:
    "field.cattle.io/projectId": "{{ .Values.projectId }}"
    "cert-manager.io/force-renewal": "true"
spec:
  secretName: "{{ .Values.name }}-{{ .Values.environment }}-{{ .Values.datacenter }}-certs"
  duration: 8760h # 1y
  renewBefore: 720h # 30d
  subject:
    countries:
      - "US"
    provinces:
      - "Ohio"
    localities:
      - "Cincinnati"
    organizations:
      - "The Kroger Co."
    organizationalUnits:
      - "Associate Technology"
  commonName: "{{ tpl (index .Values.certs.commonName .Values.environment) . }}"
  dnsNames:
    {{- range (index .Values.certs.dnsNames .Values.environment) }}
    - {{ tpl . $ }}
    {{- end }}

  issuerRef:
    name: krogerissuer
    kind: KrogerIssuer
    group: certs.kroger.com
